# Generated by Django 4.2.5 on 2023-10-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('followerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('followedID', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('watchHistoryID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
